### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/BuildBattlePE#1]
Im a Noob!
~Trolled by The Lucy Club

**Comment by ImagicalGamer** [comment]
Were gonna use the same tap to set spawn as SGV3

**Comment by ImagicalGamer** [comment]
@thelucyclub @TheDragonRing @TheKnightGamer #Squad is complete.

**Comment by Taki21** [comment]
How About 7 or 8 ??? or stick with 5?

**Comment by Taki21** [comment]
I know how to do da voting thingies

**Comment by Taki21** [comment]
btw Cant we just use GameTask in Main like SGV3?

**Comment by ImagicalGamer** [comment]
OK, 10?.

**Comment by ImagicalGamer** [comment]
We are I realized that would be eaiser.

**Comment by Taki21** [comment]
i think dats good.

**Comment by majovec** [comment]
https://github.com/Varfalomey/BuildBattlePE

**Comment by Taki21** [comment]
yup
and yup 10 is good

**Comment by ImagicalGamer** [comment]
I can separate it and make it neater later

**Comment by ImagicalGamer** [comment]
That BuildBattle doesn't work well.

**Comment by Taki21** [comment]
thx @majovec

**Comment by ImagicalGamer** [comment]
We could do a rewrite?

**Comment by Taki21** [comment]
ya but i was thinking we could make our own for better pruposes?

**Comment by Taki21** [comment]
Nooo! No rewrite! It uses CallBackTask Which Doesnt Exist Lol

**Comment by ImagicalGamer** [comment]
OK lol. I haven't looked at it much.

**Comment by ImagicalGamer** [comment]
Lets def make our own.

**Comment by Taki21** [comment]
lol xD

**Comment by ImagicalGamer** [comment]
Do we wanna use a system like it uses? When you join you are auto added to the waiting lobby?

**Comment by Taki21** [comment]
like Hypixel?

**Comment by Taki21** [comment]
:D Ya!

**Comment by ImagicalGamer** [comment]
YAYAYAYAYA

**Comment by Taki21** [comment]
Dat part will be easy but the player would have to setup the "lobby" xD

**Comment by Taki21** [comment]
Tp TO "lobby" and wait till 10 players xD

**Comment by ImagicalGamer** [comment]
Yeep.

**Comment by ImagicalGamer** [comment]
I think I already have a waiting lobby thing finished in one of my private plugs.

**Comment by Taki21** [comment]
Oh Me Know! After 2 -3 Min if there aint 10 people then start if > 2

**Comment by Taki21** [comment]
oh Lol xD

**Comment by ImagicalGamer** [comment]
Do we wanna use signs as another join option? That sounds good force start.

**Comment by Taki21** [comment]
Then we are 1 step ahead xD

**Comment by Taki21** [comment]
Yup Definetly

**Comment by ImagicalGamer** [comment]
lol

**Comment by Taki21** [comment]
Oops Lol

**Comment by Taki21** [comment]
Dats Better ahhh xD

**Comment by ImagicalGamer** [comment]
:+1: Lets get started.

**Comment by ImagicalGamer** [comment]
I think we should use a wait system like SGV3 instead of a lobby for rn.

**Comment by Taki21** [comment]
yup! after i do my stupid spanish project xD...

**Comment by Taki21** [comment]
ya that would be beter

**Comment by ImagicalGamer** [comment]
xD, Spanish is fun. I know 4 words or so xD.

**Comment by Taki21** [comment]
lol

**Comment by Taki21** [comment]
Trust me i get tons of spanish homework ... xD

**Comment by Taki21** [comment]
I WISH I WAS DONE ALREADY

**Comment by Taki21** [comment]
Whats this? 30 MINUTES LEFT TO FINISH YAYAYYA! xD

**Comment by Taki21** [comment]
i ll help then xD

**Comment by ImagicalGamer** [comment]
YAYAYAYAYA

**Comment by Taki21** [comment]
29.183721786387254763245128469 Minutes Left :D

**Comment by Taki21** [comment]
or 29.2 Minutes Lol

**Comment by ImagicalGamer** [comment]
lel

**Comment by Taki21** [comment]
LELOL

**Comment by ImagicalGamer** [comment]
How to remove an item from the creative inventory?
I wanna remove TNT, Flint and steel, and lava bucket.

**Comment by Taki21** [comment]
28.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999 Minutes Left

**Comment by Taki21** [comment]
Oh

**Comment by Taki21** [comment]
U can cancel event on BlockPlaceEvernt

**Comment by Taki21** [comment]
Event*

**Comment by ImagicalGamer** [comment]
Yea xD.

**Comment by Taki21** [comment]
Apperently im doin my homework and talking at da sametime xD

**Comment by ImagicalGamer** [comment]
Item::removeCreativeItem(Item::get(383, 54, 0)); 
I found that on PM forums but that's bad practice and does IM even support dat?

**Comment by ImagicalGamer** [comment]
lel shut up and do ur homework :stuck_out_tongue_winking_eye:

**Comment by Taki21** [comment]
Bye Earth

**Comment by Taki21** [comment]
Im Doing Homwork So I will see u in 8374786 Light Years

**Comment by ImagicalGamer** [comment]
lel

**Comment by Taki21** [comment]
LEL!? Im Done

**Comment by ImagicalGamer** [comment]
? WOWOWOWOWOW

**Comment by ImagicalGamer** [comment]
Should be set the blocks as an array like @xBeastMode did in his HG? So they can be removed?

**Comment by Taki21** [comment]
And use an foreach?

**Comment by ImagicalGamer** [comment]
We could, how did SkyWars teams reset the world? Lemme look at that.

**Comment by Taki21** [comment]
copy da worlds then paste? Not sure...

**Comment by Taki21** [comment]
or we can clear da blocks selection within da world

**Comment by ImagicalGamer** [comment]
I wouldn't copy and pase xD

**Comment by Taki21** [comment]
like WorldEdit

**Comment by Taki21** [comment]
Like World Edit

**Comment by ImagicalGamer** [comment]
We could delete the world and generate a new one like MyPlots does

**Comment by ImagicalGamer** [comment]
Have a world template

**Comment by Taki21** [comment]
I just said dat :( xD

**Comment by ImagicalGamer** [comment]
xD You did?

**Comment by Taki21** [comment]
dats what i meant by c and paste xD

**Comment by ImagicalGamer** [comment]
Ah xD.

**Comment by Taki21** [comment]
wait...why am i talking? Lol im supposed to do HW

**Comment by ImagicalGamer** [comment]
lol finish your homework mr PHP Professor

**Comment by Taki21** [comment]
sure

**Comment by Taki21** [comment]
xD

**Comment by ImagicalGamer** [comment]
for random themes can I do:
`public function getTheme(){
  	 $theme = rand(1,8);
  	 switch($theme){
  	 	case 1:
  	 		"Bunny"
  	 }
  }`

**Comment by ImagicalGamer** [comment]
Or do I need to do 1 = "Bunny"?

**Comment by Taki21** [comment]
yup

**Comment by ImagicalGamer** [comment]
Like I just committed?

**Comment by TheKnightGamer** [comment]
So much messages and I will help with the build battle  
I had made one before but let start newm

**Comment by ImagicalGamer** [comment]
lol thanks, this could be really good if we get it finished and work as a team.

**Comment by remotevase** [comment]
Can someone please tell me what build battle is? I'm still confused like @TheDragonRing always is

**Comment by ImagicalGamer** [comment]
@remotevase [HERE](http://lmgtfy.com/?q=What+is+MCPE+Build+battle%3F)

**Comment by ImagicalGamer** [comment]
hehe lol

**Comment by Taki21** [comment]
https://github.com/ImagicalGamer/BuildBattlePE/commit/08d71cb55f85bdd10d3da59dba21107c905843b4

**Comment by TheKnightGamer** [comment]
Let work as a team I was thinking of making a Build Battle plugin in ImagicalDevs but your making one.

**Comment by Taki21** [comment]
Well either way it's ImagicalGamer's Plugin

**Comment by ImagicalGamer** [comment]
It will be a team plug, just like SGV3.

**Comment by ImagicalGamer** [comment]
OHHH IM GONNA ADD THE PARTICLE SIGNS LIKE HYPIXEL

**Comment by ImagicalGamer** [comment]
Like if you do [heart] it spawns heart particles.

**Comment by Taki21** [comment]
heheheheheh xD

**Comment by ImagicalGamer** [comment]
What if we disable saving of the world? So it doesnt save then we unload and reload the world. Tada world is reset.

**Comment by Taki21** [comment]
Omg I am StupidAfter All xD

**Comment by TheKnightGamer** [comment]
That a great idea for world reset

**Comment by ImagicalGamer** [comment]
Save the world with the "arena" made then disable saving

**Comment by ImagicalGamer** [comment]
We should add a world generator after we finish the plug, so it generates arenas without them needing to be built.

**Comment by Taki21** [comment]
yup

**Comment by TheKnightGamer** [comment]
Stop nofication just stop to muchhhhh

**Comment by ImagicalGamer** [comment]
lol unsubscribe from this feed

**Comment by Taki21** [comment]
![ice_screenshot_20160426-150941](https://cloud.githubusercontent.com/assets/14851895/14830947/4a65d96c-0bc1-11e6-9fe9-fc78b222064b.png)

**Comment by Taki21** [comment]
um how do we unsave worlds : (

**Comment by ImagicalGamer** [comment]
I'm #ReadingTheDocs

**Comment by ImagicalGamer** [comment]
Look at the save-off command

**Comment by Taki21** [comment]
lol

**Comment by remotevase** [comment]
Off topic: @ImagicalGamer can u approve the SG plugin on IM forums so that I can continue posting updates please, that would be awesome. Just approve and you'll see what I mean

**Comment by ImagicalGamer** [comment]
Yea.

**Comment by Taki21** [comment]
$player->getLevel()->setAutoSave(false);
?????

**Comment by ImagicalGamer** [comment]
Lemme look.

**Comment by ImagicalGamer** [comment]
$sender->getServer()->setAutoSave(false);

**Comment by ImagicalGamer** [comment]
Thats for a command but replace with player

**Comment by Taki21** [comment]
ya we can use it hopefully if it doesnt return null -_- xD

**Comment by ImagicalGamer** [comment]
But that would disable for the entire server. We can try what @Taki21 found.

**Comment by ImagicalGamer** [comment]
lol the heart thing works but spawns the particle 10 blocks behind the sign

**Comment by Taki21** [comment]
why dont we say that:

> For Dis Plugin To Work YOU MUST NEED AUTO SAVE DISABLED
???

**Comment by ImagicalGamer** [comment]
LEL Dat works.

**Comment by ImagicalGamer** [comment]
I GOT DA PARTICLE SIGNS FIXED!

**Comment by ImagicalGamer** [comment]
I was doing 
`$t->getX()`
$t is da sign btw
when I needed to do
`$t->x`

**Comment by ImagicalGamer** [comment]
I was referring to the sign as an entity.

**Comment by ImagicalGamer** [comment]
@EpicSteve33 feel free to contribute

**Comment by EpicSteve33** [comment]
Nice 👍

**Comment by EpicSteve33** [comment]
@ImagicalGamer did you reuse code from sg?

**Comment by ImagicalGamer** [comment]
Were rewriting the gamesender into a gametask.

**Comment by EpicSteve33** [comment]
Oh lol

**Comment by ImagicalGamer** [comment]
I'm too lazy and to busy to start completely fresh.

**Comment by EpicSteve33** [comment]
So how far did you get on this

**Comment by ImagicalGamer** [comment]
Look at the readme.md and see whats done so far.

**Comment by EpicSteve33** [comment]
You should know

**Comment by ImagicalGamer** [comment]
?

**Comment by EpicSteve33** [comment]
You said idk

**Comment by ImagicalGamer** [comment]
Oh lel.

**Comment by ImagicalGamer** [comment]
The command and game task are close to being done

**Comment by ImagicalGamer** [comment]
We mostly need a voting system (@Taki21 said he can do) and a world reset( we think we can disable saving and unload/reload the world).

**Comment by EpicSteve33** [comment]
You know what we should do make a file "words.yml" and have it check this file

**Comment by ImagicalGamer** [comment]
:+1:

**Comment by EpicSteve33** [comment]
I could try to do work on this

**Comment by EpicSteve33** [comment]
I have a DrawMyThing plugin that has something like this I can use code from it

**Comment by ImagicalGamer** [comment]
That sounds kewl.

**Comment by EpicSteve33** [comment]
Btw we should make the dmt plugin better

**Comment by EpicSteve33** [comment]
Like restore it

**Comment by ImagicalGamer** [comment]
:+1: Next project :smile:

**Comment by EpicSteve33** [comment]
👌

**Comment by TheDragonRing** [comment]
Cool

**Comment by Taki21** [comment]
sadly im not done with me spanish waah xD

**Comment by ImagicalGamer** [comment]
@Taki21 there is this amazing thing called google translate! It helped me with my spanish homework and now I'm 4 words fluent in spanish!

**Comment by ImagicalGamer** [comment]
`    public function reload($lev)
    {
            $name = $lev->getFolderName();
            if ($this->main->getOwner()->getServer()->isLevelLoaded($name))
            {
                    $this->main->getOwner()->getServer()->unloadLevel($this->main->getOwner()->getServer()->getLevelByName($name));
            }
            $zip = new \ZipArchive;
            $zip->open($this->main->getOwner()->getDataFolder() . 'arenas/' . $name . '.zip');
            $zip->extractTo($this->main->getOwner()->getServer()->getDataPath() . 'worlds');
            $zip->close();
            unset($zip);
            $this->main->getOwner()->getServer()->loadLevel($name);
            return true;
    }
}`

**Comment by ImagicalGamer** [comment]
Code to reset a world.

**Comment by Taki21** [comment]
lolol

**Comment by Taki21** [comment]
no way...OMG 
JUST DO IT
https://www.youtube.com/watch?v=ZXsQAXx_ao0

**Comment by ImagicalGamer** [comment]
lmao

**Comment by Taki21** [comment]
meaning dats GONNA WORK 24/7 Bruh!

**Comment by Taki21** [comment]
And...Please Dont Let Hackers Destroy This xD
https://www.youtube.com/watch?v=NEEyOee8Ejk

**Comment by ImagicalGamer** [comment]
lol

**Comment by Taki21** [comment]
WE NEED ANTI_HACK PROTECTION! #Ya!

**Comment by ImagicalGamer** [comment]
We wont lol

**Comment by Taki21** [comment]
awww lol

**Comment by Taki21** [comment]
Thanks For Google Translate :D xD

**Comment by Taki21** [comment]
"Its So Helpful"

**Comment by Taki21** [comment]
WHAT DA! 164 COMMENTS!??!?!??!!?!?!?!?!?!?! OR 164 OUNCES OF SPAM!

**Comment by Taki21** [comment]
............
.........
......

**Comment by ImagicalGamer** [comment]
lol

**Comment by Taki21** [comment]
LOL? OLOLOLOLOL! LELLELEOLOLOL! lol...

**Comment by Taki21** [comment]
What !?

**Comment by Taki21** [comment]
0_0 Serious What!??

**Comment by ImagicalGamer** [comment]
lel less spamming MORE SPANISH HOMEWORK!!!!!! YOU GET 384728 LIGHT YEARS WORTH OF HOMEWORK!!!!!!

**Comment by ImagicalGamer** [comment]
It's now bug/error free on startup!

**Comment by Taki21** [comment]
Nooo! I GOT PWNED! ON LIFEBOAT ^%^&*^&%*&%$&^&^$*@#$%^&*

**Comment by Taki21** [comment]
My sister is lucky xD

**Comment by ImagicalGamer** [comment]
So did I but I don't ever play.

**Comment by ImagicalGamer** [comment]
@Taki21 how would your vote system work?

**Comment by Taki21** [comment]
getItemInHand

**Comment by Taki21** [comment]
If it's like green clay block vote is high u get da apoint

**Comment by ImagicalGamer** [comment]
Ah xD. Would we use arrays in config to tally votes or wat?

**Comment by remotevase** [comment]
well, you wouldnt need to save it in a config.... try another method. Give yourself a challenge!

**Comment by Taki21** [comment]
hmm without configs eh?

**Comment by Taki21** [comment]
we can use our own function create one etc

**Comment by ImagicalGamer** [comment]
:+1:

**Comment by ImagicalGamer** [comment]
how did we define $this->mode for PlayerInteractEvent? In SGV3, I'm recreating the tap spawn thing.

**Comment by ImagicalGamer** [comment]
got it xD

**Comment by ImagicalGamer** [comment]
lol I finished the plug it's on my desktop, but it's a complete rewrite of SGV3 so you can't run it with SGV3 yet.

**Comment by TheKnightGamer** [comment]
Hey don't put a vote system that will lag a server up just put random builds like Hypixel did

**Comment by ImagicalGamer** [comment]
That's what were gonna do, but ppl can vote by the item in their hand like HyPixel.

**Comment by Taki21** [comment]
@TheKnightGamer Loob back at other posts xD

**Comment by ImagicalGamer** [comment]
@Taki21 all we need now is a vote system and it will be done. I tested all features and they work. Also how do I change it from 24 players to 10 when making an arena? I tried $this->mode==10 but it never let you finish making the battle.

**Comment by Taki21** [comment]
why 2 "==" ?

**Comment by ImagicalGamer** [comment]
that's what we had on SGV3 it didn't make sense it should be 3 === but I just went with it.

**Comment by Taki21** [comment]
dats for if($this->mode **==** 10) check m y last commit

**Comment by ImagicalGamer** [comment]
Ik test it, try making an arena

**Comment by ImagicalGamer** [comment]
Does it work 4 u? I may have formatted it wrong.

**Comment by Taki21** [comment]
I cant test right now srry :{

**Comment by Taki21** [comment]
Mybe later or tomorrw

**Comment by ImagicalGamer** [comment]
I'm testing in a bit.

**Comment by Taki21** [comment]
But me can commit!

**Comment by ImagicalGamer** [comment]
Okie, we need a way to record the votes and tally them for each match. We could replace the deathmatch time as the voting period.

**Comment by Taki21** [comment]
im commiting however whats easier then configs to keep track?

**Comment by ImagicalGamer** [comment]
idk maybe like we did $this->mode but as votes.

**Comment by Taki21** [comment]
we will figure it out eventually...xD

**Comment by ImagicalGamer** [comment]
xD

**Comment by Taki21** [comment]
Um

**Comment by Taki21** [comment]
Im afraid we might have to create a GameTask from scratch in order to create a voting system,,,

**Comment by ImagicalGamer** [comment]
Figured.

**Comment by Taki21** [comment]
Im REALLY COnfused!

**Comment by ImagicalGamer** [comment]
Could be convert the deathmatch system into a voting system?

**Comment by Taki21** [comment]
![image](https://cloud.githubusercontent.com/assets/14851895/14836996/a486c1f6-0be2-11e6-9677-8325178bc74a.png)

**Comment by ImagicalGamer** [comment]
When it would teleport them to the deathmatch it takes them to one of the battle things and they can vote.

**Comment by ImagicalGamer** [comment]
lol

**Comment by Taki21** [comment]
Maybe Do u mind if i remove gametask and rewrite it?

**Comment by Taki21** [comment]
Lol

**Comment by ImagicalGamer** [comment]
Lemme download and save first

**Comment by Taki21** [comment]
ok

**Comment by ImagicalGamer** [comment]
OK u can rewrite now xD

**Comment by Taki21** [comment]
i uploaded a backup ZIP xD

**Comment by ImagicalGamer** [comment]
Okie xD

**Comment by Taki21** [comment]
want me to use dis:
`public function reload($lev) { $name = $lev->getFolderName(); if ($this->main->getOwner()->getServer()->isLevelLoaded($name)) { $this->main->getOwner()->getServer()->unloadLevel($this->main->getOwner()->getServer()->getLevelByName($name)); } $zip = new \ZipArchive; $zip->open($this->main->getOwner()->getDataFolder() . 'arenas/' . $name . '.zip'); $zip->extractTo($this->main->getOwner()->getServer()->getDataPath() . 'worlds'); $zip->close(); unset($zip); $this->main->getOwner()->getServer()->loadLevel($name); return true; } }`

**Comment by ImagicalGamer** [comment]
idc u can try, I disabled auto saving and unloaded and loaded. That would work better on servers who need some of their worlds to be saved.

**Comment by ImagicalGamer** [comment]
I'm gonna set the message for this as broken/dead/doesnt work for now, this might become a private plug.

**Comment by Taki21** [comment]
Um Ok

**Comment by ImagicalGamer** [comment]
lol :stuck_out_tongue_winking_eye:

**Comment by Taki21** [comment]
xD

**Comment by ImagicalGamer** [comment]
haha very funny changing my first post

**Comment by ImagicalGamer** [comment]
`	public function checkBorder($player){
			$level = $this->getServer()->getLevelByName($player["level"]);
			$t = new Vector2($player["x"], $player["z"]);
			$s = new Vector2($level->getSpawn()->getX(), $level->getSpawn()->getZ());
			$worlds = $this->config->get("worlds");
			foreach($worlds as $key => $value){
				if(!empty($value[$player["level"]])){
					$r = $value[$player["level"]];
				}
			}
			if($t->distance($s) >= $r){
				return true;
			}
			else
			{
				return false;
			}
		}

	public function onPlayerMove(PlayerMoveEvent $event){
		$player = $event->getPlayer();
		if($player instanceof Player){
			$border = $this->checkBorder(array("level" => $player->getLevel()->getName(), "x" => round($player->getX()), "z" => round($player->getZ())));
			if($border && !$player->hasPermission("worldborder.event.worldborder")){
				$event->setCancelled(true);
				$player->sendMessage("[WorldBorder] ".$this->config->get("message"));
			}
		}
	}`

**Comment by ImagicalGamer** [comment]
I'm using that on my UHC plug for a world border but $level->getSpawn() returns null. How to fix?

**Comment by ImagicalGamer** [comment]
I think it's how $level is defined.

**Comment by RedEnder** [comment]
@ImagicalGamer why not do `$level=$player->getLevel()->getFolderName();`
?

**Comment by Taki21** [comment]
That wont work since u cant get an integer from a string

**Comment by Taki21** [comment]
What getLevel() is doing is getting the Player's Level, which is an OBJECT. We could use getFolderName() for easier strings...

**Comment by RedEnder** [comment]
`$input = array("Santa", "Forest", "Summer", "Sun", "TV");`
 `$theme = array_rand($input);`
`$p->sendMessage(C::GRAY."Theme: ".$theme);`

**Comment by Taki21** [comment]
or we can use a config for themes!

**Comment by Taki21** [comment]
@ImagicalGamer ur probably missing a use statement

**Comment by RedEnder** [comment]
@Taki21 Lel almost forgot about a config
we also need to 
`$p->setGamemode(1);`

**Comment by Taki21** [comment]
LOL Yup!

**Comment by RedEnder** [comment]
`$content = explode(",",file_get_contents($this->plugin->getDataFolder() . "/themes/themes.txt"));
$length = count($content);
$rn = rand(0,$length-1);
$config->set("theme",$content[$rn]);
`
Idk if this will work just to give u an idea we should use a themes.txt file and have the words seprated by a comma i think its easier and better if they wanna add lots of words

**Comment by Taki21** [comment]
theres a way easier way

**Comment by Taki21** [comment]
`$this->config->set("mythemes", array("lol","troll","peanuts"));`

`$themes = $this->config->get("mythemes");`

`$theme = array_rand($themes);`

**Comment by RedEnder** [comment]
This isn't very important but when your in ur little "Pod" area after joining the game they should be in a lobby and be allowed to move or Be able to move in their Building Area but be in survival but once the game starts put them in Creative

**Comment by ImagicalGamer** [comment]
Were gonna add that

**Comment by ImagicalGamer** [comment]
I'll work on that. @Taki21 can you finish the GameTask and I'll change the tap system so it adds a lobby and stuff.

**Comment by ImagicalGamer** [comment]
[NarwhalCraft.net](http://NarwhalCraft.net) just finished site

**Comment by EpicSteve33** [comment]
this plugin died real quick XD

**Comment by RedEnder** [comment]
@ImagicalGamer he's making it private. Idk if he's privately working on it rn

**Comment by Taki21** [comment]
Sorry...It's my fault i was busy with other stuff...i'm back now!

**Comment by ImagicalGamer** [comment]
I'm working on some features rn privately but I left this open because idk where @Taki21 is goin with the game task xD.

**Comment by RedEnder** [comment]
Voting system would be pretty difficult aye?

**Comment by TheKnightGamer** [comment]
The Voting system is a little hard so please calm down.

**Comment by RedEnder** [comment]
@TheKnightGamer would make it myself but honestly would be hard to teleport everyone to each plot after every x seconds then save their votes then choose who wins sounds like a lot of tasks happening there

**Comment by TheKnightGamer** [comment]
We will do it after 15 or 10 sec then vote

**Comment by xBeastMode** [comment]
Sorry guys I am super busy with school and life. Is there something I can help with on BuildBattle?

**Comment by ImagicalGamer** [comment]
Sure @xBeastMode I will add you as a collaborator and feel free to contribute or add anything whenever.

**Comment by Taki21** [comment]
@ImagicalGamer I am really busy lately so if u feel if i abondened this plugin i didnt. I will try to commit soon :) thx in advance

**Comment by EpicSteve33** [comment]
@ImagicalGamer how will people know what to build, is there word system?

**Comment by RedEnder** [comment]
@EpicSteve33 if u look up its what i tried to make earlier $themes

**Comment by EpicSteve33** [comment]
Oh lel

**Comment by ImagicalGamer** [comment]
lol I am committing now for the theme system.

**Comment by thelucyclub** [comment]
lol look at post 1. I trolled you soo bad. xD

**Comment by ImagicalGamer** [comment]
ik xD

**Comment by thelucyclub** [comment]
Shud we cloos this? It's uh, not very prpductive. xD

**Comment by ImagicalGamer** [comment]
It's slow but steady progress

**Comment by Taki21** [comment]
Im starting to commit : )

**Comment by Taki21** [comment]
Seen my latest commit!?

**Comment by xBeastMode** [comment]
Please add API, it looks boring like this...

**Comment by xBeastMode** [comment]
Can somebody test this code please?

public function onMove(PlayerMoveEvent $e){
$p = $e->getPlayer();
$rad = 3 * 0.5 / 1.73205;
                    for($i = 0; $i < 6; ++$i){
                        $rot = $i * M_PI / 3;
                        $v = new Vector3(cos($rot), 0, sin($rot));
                        $h = mt_rand(3, 6) * 3.5;
                        $v->multiply((3.5 - $h) * $rad / 3.5);
                        $v->y = 0.5 + $h;
                        $cos = cos($rot);
                        $sin = sin($rot);
                        $x = $v->y * $cos - $v->z * $sin;
                        $z = $v->y * $sin + $v->z * $cos;
                        $v->y = $x;
                        $v->z = $z;
                        $p->add($v);
                        $p->getLevel()->addParticle(new DustParticle($p, 255, 0, 0));
                        $p->subtract($v);
                        $cos = cos(M_PI);
                        $sin = sin(M_PI);
                        $y = $v->y * $cos - $v->z * $sin;
                        $z = $v->y * $sin + $v->z * $cos;
                        $v->y = $y;
                        $v->z = $z;
                        $cos = cos(M_PI / 2);
                        $sin = sin(M_PI / 2);
                        $x = $v->x * $cos + $v->z * $sin;
                        $z = $v->x * -$sin + $v->z * $cos;
                        $v->x = $x;
                        $v->z = $z;
                        $p->add($v);
                        $p->getLevel()->addParticle(new DustParticle($p, 255, 0, 0));
                        $p->subtract($v);
                    }
}

**Comment by EpicSteve33** [comment]
I don't think that will work

**Comment by xBeastMode** [comment]
Why? Have you actually tested it?

**Comment by EpicSteve33** [comment]
I will test it now lol

**Comment by EpicSteve33** [comment]
does not pull players back

**Comment by EpicSteve33** [comment]
@xBeastMode no errors and no messages but players can move around

**Comment by RedEnder** [comment]
@EpicSteve33 are you using Genisys?

**Comment by xBeastMode** [comment]
It's supposed to create a star particle

**Comment by EpicSteve33** [comment]
Oh so its not supposed pull players back?

**Comment by xBeastMode** [comment]
No!!! And could you plz just try it instead of discussing so much?!

**Comment by EpicSteve33** [comment]
I didn't test the particles lol

**Comment by Taki21** [comment]
OMG! So much comments!

**Comment by EpicSteve33** [comment]
I cannot load this page on my pc any more it crashes my browser

**Comment by Taki21** [comment]
276 comments

**Comment by EpicSteve33** [comment]
Lol

**Comment by ImagicalGamer** [comment]
same it crashes my browser.

**Comment by RedEnder** [comment]
@ImagicalGamer THE STRUGGLE

**Comment by Taki21** [comment]
Nope not me : )

**Comment by ImagicalGamer** [comment]
Dead or na?:cry:

**Comment by ImagicalGamer** [comment]
:+1:

**Comment by remotevase** [comment]
Sorry, @ImagicalGamer I'm not gonna work on this- BBPE

**Comment by EpicSteve33** [comment]
@ImagicalGamer I would help on this but I have been really busy

**Comment by TheKnightGamer** [comment]
Hey could we do a rewrite of this plugin or continue it

**Comment by Driesboy** [comment]
i cannot i am working on a new server update
but it is done i will help
