### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Taki21** [ImagicalGamer/BuildBattlePE#2]
HELP! @ImagicalGamer #SQUAD!
- So...
I have a pizza...JK

ok so how would we tp everyone to everybodies "builds to vote?" Im stuck on dat part ... any suggestions!? plz
thx in advance

**Comment by TheKnightGamer** [comment]
Random tp

**Comment by remotevase** [comment]
Not sure... I think @TheKnightGamer is right, random tp ing those people

**Comment by Taki21** [comment]
random tp?

**Comment by Taki21** [comment]
I mean like how would we get each player to tp to each build then vote? Im not very sure

**Comment by ImagicalGamer** [comment]
We could use a delayed task? We could use the same system we use for the players to join the match at diff points and teleport them all there.

**Comment by TheKnightGamer** [comment]
Or you see like SG deathmatch where you get to well you put a tp position and every 10sec you get tp there.

**Comment by thelucyclub** [comment]
@TheKnightGamer The flash!

**Comment by TheKnightGamer** [comment]
@thelucyclub hmmmm the flash is fast let just put it 20 second.

**Comment by thelucyclub** [comment]
Hmm u know english your bads!
